### ISSUE TITLE
Frozen ticks vignette being overriden with Pumpkin opacity setting!!!

### ISSUE THREAD

**Issue by Dreig-Michihi** [MicrocontrollersDev/OverlayTweaks#16]
Recorded the bug on the video. Access with link.
https://youtu.be/l1eFWQx82fY

**Comment by MicrocontrollersDev** [comment]
i’ll be busy for a bit but i’ll fix these as soon as i can

**Comment by MicrocontrollersDev** [comment]
This should be fixed in 1.6.1 https://modrinth.com/mod/overlaytweaks/version/1.6.1

**Comment by Dreig-Michihi** [comment]
> This should be fixed in 1.6.1 https://modrinth.com/mod/overlaytweaks/version/1.6.1

wow! Thank you very much for such fast fix

**Comment by Dreig-Michihi** [comment]
> This should be fixed in 1.6.1 https://modrinth.com/mod/overlaytweaks/version/1.6.1

I just tested it, and wasn't fixed well. You've add an option for the Frozen ticks overlay, but it doesn't solve the main issue with it.
Frozen ticks overlay in vanilla shows degree of freezing, it slowly changes it's opacity in game.

The easiest solution to solve the issue would be to add a toggle button, to get vanilla Freeze Ticks overlay

**Comment by Dreig-Michihi** [comment]
> > This should be fixed in 1.6.1 https://modrinth.com/mod/overlaytweaks/version/1.6.1
> 
> I just tested it, and it wasn't fixed well. You've add an option for the Frozen ticks overlay, but it doesn't solve the main issue with it. Frozen ticks overlay in vanilla shows degree of freezing, it slowly changes it's opacity in game.
> 
> The easiest solution to solve the issue would be to add a toggle button, to get vanilla Freeze Ticks overlay

**Comment by MicrocontrollersDev** [comment]
I knew I should have tested how vanilla works. This is my bad, I forgot how the effect works. I'll fix this asap

**Comment by MicrocontrollersDev** [comment]
> The easiest solution to solve the issue would be to add a toggle button, to get vanilla Freeze Ticks overlay

I've come up with a better solution that I think works better. Just multiply the vanilla value by the mod config value. That way its the same as vanilla at 100%.

Basically, say it takes 2 seconds to get to full opacity in vanilla (and equivalently 100% in the mod config). if its set to 50%, at 2 seconds it will be at the same opacity it was at 100% at 1 second.

In short, the % you set in the config will be the max opacity and the lower the number is the longer it will take to get to that opacity, if that makes any sense. Regardless, this should be identical to vanilla while its at 100%

**Comment by MicrocontrollersDev** [comment]
please try out 1.6.2 https://modrinth.com/mod/overlaytweaks/version/1.6.2 and let me know if its alright now. thanks

**Comment by Dreig-Michihi** [comment]
> please try out 1.6.2 https://modrinth.com/mod/overlaytweaks/version/1.6.2 and let me know if its alright now. thanks

tried, seems to work well! Thank you
